package lab8;

import java.awt.Color;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JColorChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
        ap.cargarPersonas();
        cargarPersonasCB();
        aa.cargarArticulos();
        cargarArticulosCB();
        rm.cargarMensajes();
        cargarMensajes();

        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg_sexo = new javax.swing.ButtonGroup();
        bg_estadoCivil = new javax.swing.ButtonGroup();
        bg_cargo = new javax.swing.ButtonGroup();
        panel = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        cb_tipo = new javax.swing.JComboBox<>();
        ff_identificacion = new javax.swing.JFormattedTextField();
        jLabel1 = new javax.swing.JLabel();
        tf_nombre = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        ff_edad = new javax.swing.JFormattedTextField();
        jLabel3 = new javax.swing.JLabel();
        rb_masculino = new javax.swing.JRadioButton();
        rb_femenino = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        rb_soltero = new javax.swing.JRadioButton();
        rb_casado = new javax.swing.JRadioButton();
        rb_divorciado = new javax.swing.JRadioButton();
        rb_viudo = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();
        ff_altura = new javax.swing.JFormattedTextField();
        jLabel7 = new javax.swing.JLabel();
        ff_peso = new javax.swing.JFormattedTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jl_usuario = new javax.swing.JLabel();
        tf_usuario = new javax.swing.JTextField();
        jl_contra = new javax.swing.JLabel();
        tf_contra = new javax.swing.JTextField();
        rb_sucursal = new javax.swing.JRadioButton();
        rb_planta = new javax.swing.JRadioButton();
        jl_cargo = new javax.swing.JLabel();
        jl_ocupacion = new javax.swing.JLabel();
        tf_ocupacion = new javax.swing.JTextField();
        tf_horario = new javax.swing.JTextField();
        jl_horario = new javax.swing.JLabel();
        ff_tiempo = new javax.swing.JFormattedTextField();
        jl_tiempo = new javax.swing.JLabel();
        jl_semanas = new javax.swing.JLabel();
        jb_crear = new javax.swing.JButton();
        jb_modificar = new javax.swing.JButton();
        jb_eliminar = new javax.swing.JButton();
        cb_personas = new javax.swing.JComboBox<>();
        ff_sueldo = new javax.swing.JFormattedTextField();
        jl_sueldo = new javax.swing.JLabel();
        jl_modificableU = new javax.swing.JLabel();
        jl_modificableS = new javax.swing.JLabel();
        jl_semanas1 = new javax.swing.JLabel();
        jb_limpiar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        cb_art = new javax.swing.JComboBox<>();
        jb_color = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        tf_titulo = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ta_descripcionArt = new javax.swing.JTextArea();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        tf_editorial = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        ff_tamano = new javax.swing.JFormattedTextField();
        jLabel16 = new javax.swing.JLabel();
        sl_estado = new javax.swing.JSlider();
        jl_numeros = new javax.swing.JLabel();
        jl_estado = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        cb_registrador = new javax.swing.JComboBox<>();
        jLabel20 = new javax.swing.JLabel();
        jl_garantia = new javax.swing.JLabel();
        jl_edicion = new javax.swing.JLabel();
        jl_volumen = new javax.swing.JLabel();
        ff_volumen = new javax.swing.JFormattedTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        ta_descripcionComic = new javax.swing.JTextArea();
        jl_casaElaboracion = new javax.swing.JLabel();
        tf_casaElaboracion = new javax.swing.JTextField();
        jl_desc = new javax.swing.JLabel();
        tf_pais = new javax.swing.JTextField();
        jl_pais = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        ta_instrucciones = new javax.swing.JTextArea();
        jl_instrucciones = new javax.swing.JLabel();
        jb_crearArt = new javax.swing.JButton();
        jb_modificarArt = new javax.swing.JButton();
        jb_eliminarArt = new javax.swing.JButton();
        ff_garantía = new javax.swing.JFormattedTextField();
        ff_edicion = new javax.swing.JFormattedTextField();
        cb_listaArt = new javax.swing.JComboBox<>();
        sp_puntuacion = new javax.swing.JSpinner();
        jb_limpiar1 = new javax.swing.JButton();
        jl_modificableU1 = new javax.swing.JLabel();
        jl_modificableU2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jt_personas = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        text = new javax.swing.JTextArea();
        cb_emisor = new javax.swing.JComboBox<>();
        cb_receptor = new javax.swing.JComboBox<>();
        bt_enviarMensaje = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        jt_mensajes = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        panel.setBackground(new java.awt.Color(204, 204, 255));

        jTabbedPane1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTabbedPane1FocusGained(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(153, 153, 255));

        cb_tipo.setBackground(new java.awt.Color(255, 51, 51));
        cb_tipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Gerente", "Persona General" }));
        cb_tipo.setSelectedIndex(1);
        cb_tipo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cb_tipoItemStateChanged(evt);
            }
        });

        try {
            ff_identificacion.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("####-####-#####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Identificación:");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Nombre:");

        ff_edad.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Edad:");

        rb_masculino.setBackground(new java.awt.Color(153, 153, 255));
        bg_sexo.add(rb_masculino);
        rb_masculino.setSelected(true);
        rb_masculino.setText("Masculino");

        rb_femenino.setBackground(new java.awt.Color(153, 153, 255));
        bg_sexo.add(rb_femenino);
        rb_femenino.setText("Femenino");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Estado Civil:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("Sexo:");

        rb_soltero.setBackground(new java.awt.Color(153, 153, 255));
        bg_estadoCivil.add(rb_soltero);
        rb_soltero.setSelected(true);
        rb_soltero.setText("Soltero");

        rb_casado.setBackground(new java.awt.Color(153, 153, 255));
        bg_estadoCivil.add(rb_casado);
        rb_casado.setText("Casado");

        rb_divorciado.setBackground(new java.awt.Color(153, 153, 255));
        bg_estadoCivil.add(rb_divorciado);
        rb_divorciado.setText("Divorciado");

        rb_viudo.setBackground(new java.awt.Color(153, 153, 255));
        bg_estadoCivil.add(rb_viudo);
        rb_viudo.setText("Viudo");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("Altura:");

        ff_altura.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel7.setText("cm");

        ff_peso.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel8.setText("kilos");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setText("Peso:");

        jl_usuario.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jl_usuario.setText("Usuario:");

        tf_usuario.setEnabled(false);

        jl_contra.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jl_contra.setText("Contraseña:");

        tf_contra.setEnabled(false);

        rb_sucursal.setBackground(new java.awt.Color(153, 153, 255));
        bg_cargo.add(rb_sucursal);
        rb_sucursal.setText("Gerente de sucursal");
        rb_sucursal.setEnabled(false);

        rb_planta.setBackground(new java.awt.Color(153, 153, 255));
        bg_cargo.add(rb_planta);
        rb_planta.setSelected(true);
        rb_planta.setText("Gerente de planta");
        rb_planta.setEnabled(false);

        jl_cargo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jl_cargo.setText("Cargo:");

        jl_ocupacion.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jl_ocupacion.setText("Ocupación:");

        jl_horario.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jl_horario.setText("Horario de trabajo:");

        ff_tiempo.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));

        jl_tiempo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jl_tiempo.setText("Tiempo trabajando:");

        jl_semanas.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jl_semanas.setText("semanas");

        jb_crear.setBackground(new java.awt.Color(255, 153, 51));
        jb_crear.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jb_crear.setText("CREAR");
        jb_crear.setBorderPainted(false);
        jb_crear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_crearActionPerformed(evt);
            }
        });

        jb_modificar.setBackground(new java.awt.Color(255, 153, 0));
        jb_modificar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jb_modificar.setText("MODIFICAR");
        jb_modificar.setBorderPainted(false);
        jb_modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_modificarActionPerformed(evt);
            }
        });

        jb_eliminar.setBackground(new java.awt.Color(255, 153, 0));
        jb_eliminar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jb_eliminar.setText("ELIMINAR");
        jb_eliminar.setBorderPainted(false);
        jb_eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_eliminarActionPerformed(evt);
            }
        });

        cb_personas.setBackground(new java.awt.Color(255, 0, 51));
        cb_personas.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cb_personasItemStateChanged(evt);
            }
        });

        ff_sueldo.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));

        jl_sueldo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jl_sueldo.setText("Sueldo:");

        jl_modificableU.setForeground(new java.awt.Color(255, 0, 0));
        jl_modificableU.setText("*modificable");

        jl_modificableS.setForeground(new java.awt.Color(255, 0, 0));
        jl_modificableS.setText("*modificable");

        jl_semanas1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jl_semanas1.setText("Lempiras");

        jb_limpiar.setBackground(new java.awt.Color(255, 153, 51));
        jb_limpiar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jb_limpiar.setText("LIMPIAR");
        jb_limpiar.setBorderPainted(false);
        jb_limpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_limpiarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(ff_altura, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel7))
                    .addComponent(jLabel1)
                    .addComponent(ff_identificacion, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(jl_ocupacion)
                    .addComponent(tf_ocupacion, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_horario, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jl_horario)
                    .addComponent(tf_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jl_usuario)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jl_modificableU)))
                .addGap(33, 33, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(tf_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(jl_contra)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(ff_peso, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel8))
                    .addComponent(jl_tiempo)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(ff_tiempo, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jl_semanas, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jl_sueldo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jl_modificableS))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tf_contra, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(ff_sueldo, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jl_semanas1, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(80, 80, 80)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rb_sucursal)
                            .addComponent(jl_cargo)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(rb_casado)
                                    .addComponent(rb_soltero)
                                    .addComponent(jLabel4)
                                    .addComponent(rb_masculino))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(rb_femenino)
                                    .addComponent(rb_divorciado)
                                    .addComponent(rb_viudo)))
                            .addComponent(jLabel3)
                            .addComponent(ff_edad, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)
                            .addComponent(rb_planta))))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(cb_personas, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jb_limpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jb_modificar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jb_eliminar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jb_crear, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(cb_tipo, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(44, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(0, 86, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(ff_identificacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tf_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(26, 26, 26)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ff_edad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cb_tipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(rb_femenino)
                                .addComponent(jb_crear))
                            .addComponent(rb_masculino, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(ff_peso, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(ff_altura, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jl_tiempo, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jl_ocupacion, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rb_soltero, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(rb_divorciado, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jl_semanas, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(ff_tiempo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tf_ocupacion, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jl_modificableS, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jl_sueldo, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jl_horario, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(rb_casado, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(rb_viudo, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(ff_sueldo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jl_cargo)
                                .addComponent(jl_semanas1))
                            .addComponent(tf_horario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jl_usuario, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jl_modificableU, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jl_contra, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(rb_planta, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addComponent(cb_personas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jb_modificar)
                        .addGap(18, 18, 18)
                        .addComponent(jb_eliminar)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(tf_contra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(rb_sucursal))
                    .addComponent(tf_usuario, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addComponent(jb_limpiar)
                .addGap(62, 62, 62))
        );

        jTabbedPane1.addTab("Personas", jPanel1);

        jPanel2.setBackground(new java.awt.Color(102, 204, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cb_art.setBackground(new java.awt.Color(0, 0, 255));
        cb_art.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Comic", "Juego", "Figura" }));
        cb_art.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cb_artItemStateChanged(evt);
            }
        });
        jPanel2.add(cb_art, new org.netbeans.lib.awtextra.AbsoluteConstraints(604, 21, 132, -1));

        jb_color.setBackground(new java.awt.Color(255, 0, 0));
        jb_color.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jb_color.setBorderPainted(false);
        jb_color.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_colorActionPerformed(evt);
            }
        });
        jPanel2.add(jb_color, new org.netbeans.lib.awtextra.AbsoluteConstraints(96, 54, 123, 28));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel10.setText("Color:");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(41, 54, 45, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel11.setText("Tiítulo:");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 23, -1, -1));
        jPanel2.add(tf_titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(94, 21, 125, -1));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel12.setText("Descripción");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(242, 21, -1, 20));

        ta_descripcionArt.setColumns(20);
        ta_descripcionArt.setRows(5);
        jScrollPane1.setViewportView(ta_descripcionArt);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(317, 21, 251, 68));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel13.setText("del artículo:");
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(225, 47, 86, -1));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel14.setText("Editorial:");
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(317, 100, -1, -1));
        jPanel2.add(tf_editorial, new org.netbeans.lib.awtextra.AbsoluteConstraints(423, 95, 147, -1));

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel15.setText("Tamaño:");
        jPanel2.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 96, -1, -1));

        ff_tamano.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        jPanel2.add(ff_tamano, new org.netbeans.lib.awtextra.AbsoluteConstraints(94, 94, 105, -1));

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel16.setText("cm");
        jPanel2.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(203, 94, -1, -1));

        sl_estado.setMaximum(10);
        sl_estado.setMinimum(1);
        jPanel2.add(sl_estado, new org.netbeans.lib.awtextra.AbsoluteConstraints(39, 148, -1, -1));

        jl_numeros.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jl_numeros.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jl_numeros.setText("1   2   3   4   5   6   7   8   9   10");
        jPanel2.add(jl_numeros, new org.netbeans.lib.awtextra.AbsoluteConstraints(39, 178, 200, -1));

        jl_estado.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jl_estado.setText("Estado:");
        jPanel2.add(jl_estado, new org.netbeans.lib.awtextra.AbsoluteConstraints(39, 126, -1, -1));

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel19.setText("Puntuación:");
        jPanel2.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(317, 131, -1, -1));

        cb_registrador.setBackground(new java.awt.Color(255, 0, 51));
        cb_registrador.setModel(cb_personas.getModel());
        cb_registrador.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cb_registradorItemStateChanged(evt);
            }
        });
        jPanel2.add(cb_registrador, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 160, 147, -1));

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel20.setText("Registrado por:");
        jPanel2.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 160, -1, -1));

        jl_garantia.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jl_garantia.setText("Tiempo de garantía:");
        jPanel2.add(jl_garantia, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, 130, -1));

        jl_edicion.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jl_edicion.setText("No. de Edición:");
        jPanel2.add(jl_edicion, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, -1, -1));

        jl_volumen.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jl_volumen.setText("No. de Volumen:");
        jPanel2.add(jl_volumen, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, -1, -1));

        ff_volumen.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        jPanel2.add(ff_volumen, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 200, 96, -1));

        ta_descripcionComic.setColumns(20);
        ta_descripcionComic.setRows(5);
        jScrollPane2.setViewportView(ta_descripcionComic);

        jPanel2.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, 210, 120));

        jl_casaElaboracion.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jl_casaElaboracion.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jl_casaElaboracion.setText("Casa de elaboración:");
        jPanel2.add(jl_casaElaboracion, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 190, -1, -1));

        tf_casaElaboracion.setEnabled(false);
        jPanel2.add(tf_casaElaboracion, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 190, 150, -1));

        jl_desc.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jl_desc.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jl_desc.setText("Descripción:");
        jPanel2.add(jl_desc, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, 90, -1));

        tf_pais.setEnabled(false);
        jPanel2.add(tf_pais, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 220, 150, -1));

        jl_pais.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jl_pais.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jl_pais.setText("País donde se realizó:");
        jPanel2.add(jl_pais, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 220, -1, -1));

        ta_instrucciones.setColumns(20);
        ta_instrucciones.setRows(5);
        ta_instrucciones.setEnabled(false);
        jScrollPane3.setViewportView(ta_instrucciones);

        jPanel2.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 280, 280, 150));

        jl_instrucciones.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jl_instrucciones.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jl_instrucciones.setText("Instrucciones de armado:");
        jPanel2.add(jl_instrucciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 260, -1, -1));

        jb_crearArt.setBackground(new java.awt.Color(255, 153, 51));
        jb_crearArt.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jb_crearArt.setText("CREAR");
        jb_crearArt.setBorderPainted(false);
        jb_crearArt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_crearArtActionPerformed(evt);
            }
        });
        jPanel2.add(jb_crearArt, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 70, 100, -1));

        jb_modificarArt.setBackground(new java.awt.Color(255, 153, 0));
        jb_modificarArt.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jb_modificarArt.setText("MODIFICAR");
        jb_modificarArt.setBorderPainted(false);
        jb_modificarArt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_modificarArtActionPerformed(evt);
            }
        });
        jPanel2.add(jb_modificarArt, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 190, -1, -1));

        jb_eliminarArt.setBackground(new java.awt.Color(255, 153, 0));
        jb_eliminarArt.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jb_eliminarArt.setText("ELIMINAR");
        jb_eliminarArt.setBorderPainted(false);
        jb_eliminarArt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_eliminarArtActionPerformed(evt);
            }
        });
        jPanel2.add(jb_eliminarArt, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 220, 100, -1));

        ff_garantía.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        ff_garantía.setEnabled(false);
        jPanel2.add(ff_garantía, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 260, 96, -1));

        ff_edicion.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        ff_edicion.setEnabled(false);
        jPanel2.add(ff_edicion, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 230, 96, -1));

        cb_listaArt.setBackground(new java.awt.Color(0, 0, 255));
        cb_listaArt.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cb_listaArtItemStateChanged(evt);
            }
        });
        jPanel2.add(cb_listaArt, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 150, 132, 20));

        sp_puntuacion.setModel(new javax.swing.SpinnerNumberModel(Float.valueOf(100.0f), Float.valueOf(1.0f), Float.valueOf(100.0f), Float.valueOf(1.0f)));
        jPanel2.add(sp_puntuacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 130, 150, -1));

        jb_limpiar1.setBackground(new java.awt.Color(255, 153, 51));
        jb_limpiar1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jb_limpiar1.setText("LIMPIAR");
        jb_limpiar1.setBorderPainted(false);
        jb_limpiar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_limpiar1ActionPerformed(evt);
            }
        });
        jPanel2.add(jb_limpiar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 340, -1, -1));

        jl_modificableU1.setForeground(new java.awt.Color(255, 0, 0));
        jl_modificableU1.setText("*modificable");
        jPanel2.add(jl_modificableU1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 290, -1, -1));

        jl_modificableU2.setForeground(new java.awt.Color(255, 0, 0));
        jl_modificableU2.setText("*modificable");
        jPanel2.add(jl_modificableU2, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 240, -1, -1));

        jTabbedPane1.addTab("Artículos", jPanel2);

        jPanel3.setBackground(new java.awt.Color(255, 153, 51));

        jt_personas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Rol"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane4.setViewportView(jt_personas);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 712, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(33, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(202, 202, 202))
        );

        jTabbedPane1.addTab("Listado", jPanel3);

        jPanel4.setBackground(new java.awt.Color(0, 204, 51));

        text.setColumns(20);
        text.setRows(5);
        jScrollPane5.setViewportView(text);

        cb_emisor.setBackground(new java.awt.Color(255, 0, 51));
        cb_emisor.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cb_emisorItemStateChanged(evt);
            }
        });

        cb_receptor.setBackground(new java.awt.Color(255, 0, 51));
        cb_receptor.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cb_receptorItemStateChanged(evt);
            }
        });

        bt_enviarMensaje.setBackground(new java.awt.Color(0, 255, 255));
        bt_enviarMensaje.setText("Enviar Mensaje");
        bt_enviarMensaje.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        bt_enviarMensaje.setBorderPainted(false);
        bt_enviarMensaje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_enviarMensajeActionPerformed(evt);
            }
        });

        jLabel17.setText("Emisor:");

        jLabel18.setText("Receptor:");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(cb_emisor, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(52, 52, 52)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(bt_enviarMensaje, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 301, Short.MAX_VALUE)))
                    .addComponent(jLabel17))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cb_receptor, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18))
                .addGap(39, 39, 39))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(jLabel18))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cb_receptor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cb_emisor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 204, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(bt_enviarMensaje)
                .addGap(95, 95, 95))
        );

        jTabbedPane1.addTab("Mensajería", jPanel4);

        jPanel5.setBackground(new java.awt.Color(102, 255, 255));

        jt_mensajes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Emisor", "Receptor", "Mensaje"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane6.setViewportView(jt_mensajes);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 565, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(136, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 373, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(62, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Mensajes", jPanel5);

        javax.swing.GroupLayout panelLayout = new javax.swing.GroupLayout(panel);
        panel.setLayout(panelLayout);
        panelLayout.setHorizontalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelLayout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 768, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        panelLayout.setVerticalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelLayout.createSequentialGroup()
                .addGap(0, 63, Short.MAX_VALUE)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 474, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jb_crearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_crearActionPerformed

        if (entrar()) {
            long identificacion;
            int edad, altura, peso;
            String nombrePersona, sexo, estadoCivil;

            try {
                String id = ff_identificacion.getText();
                identificacion = Long.parseLong(id.substring(0, 4) + id.substring(5, 9) + id.substring(10));
                edad = Integer.parseInt(ff_edad.getText());
                altura = Integer.parseInt(ff_altura.getText());
                peso = Integer.parseInt(ff_peso.getText());

                nombrePersona = tf_nombre.getText();

                sexo = (rb_masculino.isSelected()) ? "Masculino" : "Femenino";

                if (rb_soltero.isSelected()) {
                    estadoCivil = "Soltero";
                } else if (rb_casado.isSelected()) {
                    estadoCivil = "Casado";
                } else if (rb_divorciado.isSelected()) {
                    estadoCivil = "Divorciado";
                } else {
                    estadoCivil = "Viudo";
                }

                if (cb_tipo.getSelectedIndex() == 0) {

                    String usuario, contra, cargo;
                    usuario = tf_usuario.getText();
                    contra = tf_contra.getText();
                    cargo = (rb_planta.isSelected()) ? "Gerente de planta" : "Gerente de sucursal";

                    Persona p = new Gerente(usuario, contra, cargo, identificacion, nombrePersona, edad, sexo, estadoCivil, altura, peso);

                    ap.getPersonas().add(p);
                    DefaultComboBoxModel m = (DefaultComboBoxModel) cb_personas.getModel();
                    m.addElement(p);

                    estadoOperacion(true);
                } else if (cb_tipo.getSelectedIndex() == 1) {
                    String ocupacion, horario;
                    int tiempo;
                    float sueldo;

                    ocupacion = tf_ocupacion.getText();
                    horario = tf_horario.getText();
                    tiempo = Integer.parseInt(ff_tiempo.getText());
                    sueldo = Float.parseFloat(ff_sueldo.getText());
                    Persona p = new PersonaGeneral(ocupacion, horario, tiempo, sueldo, identificacion, nombrePersona, edad, sexo, estadoCivil, altura, peso);

                    ap.getPersonas().add(p);
                    DefaultComboBoxModel m = (DefaultComboBoxModel) cb_personas.getModel();
                    m.addElement(p);

                    estadoOperacion(true);
                }
                ap.escribirPersonas();
                limpiarCampos();
                cargarPersonasCB();

            } catch (Exception e) {
                estadoOperacion(false);
            }

        }
    }//GEN-LAST:event_jb_crearActionPerformed

    private void cb_tipoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cb_tipoItemStateChanged
        if (evt.getStateChange() == 2) {
            if (cb_tipo.getSelectedIndex() == 0) {
//                jl_usuario.setVisible(true);
//                jl_cargo.setVisible(true);
//                jl_contra.setVisible(true);
//                jl_modificableU.setVisible(true);
                tf_usuario.setEnabled(true);
                tf_contra.setEnabled(true);
                rb_planta.setEnabled(true);
                rb_sucursal.setEnabled(true);

                //Set not visible the others
//                jl_ocupacion.setVisible(false);
//                jl_horario.setVisible(false);
//                jl_tiempo.setVisible(false);
//                jl_semanas.setVisible(false);
//                jl_sueldo.setVisible(false);
//                jl_modificableS.setVisible(false);
                tf_ocupacion.setEnabled(false);
                tf_horario.setEnabled(false);
                ff_tiempo.setEnabled(false);
                ff_sueldo.setEnabled(false);
            } else if (cb_tipo.getSelectedIndex() == 1) {
//                jl_ocupacion.setVisible(true);
//                jl_horario.setVisible(true);
//                jl_tiempo.setVisible(true);
//                jl_semanas.setVisible(true);
//                jl_sueldo.setVisible(true);
//                jl_modificableS.setVisible(true);
                tf_ocupacion.setEnabled(true);
                tf_horario.setEnabled(true);
                ff_tiempo.setEnabled(true);
                ff_sueldo.setEnabled(true);

                //Set not visible the others
//                jl_usuario.setVisible(false);
//                jl_cargo.setVisible(false);
//                jl_contra.setVisible(false);
//                jl_modificableU.setVisible(false);
                tf_usuario.setEnabled(false);
                tf_contra.setEnabled(false);
                rb_planta.setEnabled(false);
                rb_sucursal.setEnabled(false);
            }
        }
    }//GEN-LAST:event_cb_tipoItemStateChanged

    private void jb_eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_eliminarActionPerformed
        if (entrar()) {
            try {
                if (cb_personas.getSelectedIndex() >= 0) {
                    ap.getPersonas().remove(cb_personas.getSelectedIndex());
                    DefaultComboBoxModel m = (DefaultComboBoxModel) cb_personas.getModel();
                    m.removeElementAt(cb_personas.getSelectedIndex());
                    estadoOperacion(true);
                    ap.escribirPersonas();
                    cargarPersonasCB();
                }
            } catch (Exception e) {
                estadoOperacion(false);
            }
        }

    }//GEN-LAST:event_jb_eliminarActionPerformed

    private void jb_modificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_modificarActionPerformed

        if (entrar()) {
            long identificacion;
            int edad, altura, peso;
            String nombrePersona, sexo, estadoCivil;

            try {
                String id = ff_identificacion.getText();
                identificacion = Long.parseLong(id.substring(0, 4) + id.substring(5, 9) + id.substring(10));
                edad = Integer.parseInt(ff_edad.getText());
                altura = Integer.parseInt(ff_altura.getText());
                peso = Integer.parseInt(ff_peso.getText());

                nombrePersona = tf_nombre.getText();

                sexo = (rb_masculino.isSelected()) ? "Masculino" : "Femenino";

                if (rb_soltero.isSelected()) {
                    estadoCivil = "Soltero";
                } else if (rb_casado.isSelected()) {
                    estadoCivil = "Casado";
                } else if (rb_divorciado.isSelected()) {
                    estadoCivil = "Divorciado";
                } else {
                    estadoCivil = "Viudo";
                }

                if (ap.getPersonas().get(cb_personas.getSelectedIndex()) instanceof Gerente) {
                    String usuario = tf_usuario.getText();
                    Gerente g = ((Gerente) ap.getPersonas().get(cb_personas.getSelectedIndex()));//((Gerente) cb_personas.getSelectedItem());
                    g.setUsuario(usuario);

                    g.setNombrePersona(nombrePersona);
                    g.setAltura(altura);
                    g.setEstadoCivil(estadoCivil);
                    g.setIdentificacion(identificacion);
                    g.setPeso(peso);
                    g.setSexo(sexo);
                    g.setEdad(edad);

                    estadoOperacion(true);
                } else if (ap.getPersonas().get(cb_personas.getSelectedIndex()) instanceof PersonaGeneral) {

                    Float sueldo = Float.parseFloat(ff_sueldo.getText());

                    PersonaGeneral g = ((PersonaGeneral) ap.getPersonas().get(cb_personas.getSelectedIndex()));
                    g.setSueldo(sueldo);

                    g.setNombrePersona(nombrePersona);
                    g.setAltura(altura);
                    g.setEstadoCivil(estadoCivil);
                    g.setIdentificacion(identificacion);
                    g.setPeso(peso);
                    g.setSexo(sexo);
                    g.setEdad(edad);

                    estadoOperacion(true);
                }
                ap.escribirPersonas();
                cargarPersonasCB();
            } catch (Exception e) {
                estadoOperacion(false);
            }
            limpiarCampos();
        }
    }//GEN-LAST:event_jb_modificarActionPerformed

    private void cb_personasItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cb_personasItemStateChanged
        if (evt.getStateChange() == 2 && cb_personas.getSelectedIndex() >= 0) {

            DefaultComboBoxModel model = (DefaultComboBoxModel) cb_personas.getModel();
            if (model.getElementAt(cb_personas.getSelectedIndex()) instanceof Gerente) {

                Gerente g = (Gerente) cb_personas.getSelectedItem();
                mostrarDatosPersona(g);

                //Set not visible 
//                jl_ocupacion.setVisible(false);
//                jl_horario.setVisible(false);
//                jl_tiempo.setVisible(false);
//                jl_semanas.setVisible(false);
//                jl_sueldo.setVisible(false);
//                jl_modificableS.setVisible(false);
                tf_ocupacion.setEnabled(false);
                tf_horario.setEnabled(false);
                ff_tiempo.setEnabled(false);
                ff_sueldo.setEnabled(false);

//                jl_usuario.setVisible(true);
//                jl_cargo.setVisible(true);
//                jl_contra.setVisible(true);
//                jl_modificableU.setVisible(true);
                tf_usuario.setEnabled(true);
                tf_usuario.setText(g.getUsuario());

                tf_contra.setEnabled(true);
                tf_contra.setText(g.getContraseña());

                rb_planta.setEnabled(true);
                rb_sucursal.setEnabled(true);
                if (g.getCargo().equals("Gerente de planta")) {
                    rb_planta.setSelected(true);
                    rb_sucursal.setSelected(false);
                } else {
                    rb_planta.setSelected(false);
                    rb_sucursal.setSelected(true);
                }

                tf_ocupacion.setText("");
                tf_horario.setText("");
                ff_tiempo.setText("");
                ff_sueldo.setText("");

                cb_tipo.setSelectedIndex(0);
                
            } else {
                PersonaGeneral p = (PersonaGeneral) cb_personas.getSelectedItem();
                mostrarDatosPersona(p);

                //Set not visible 
//                jl_usuario.setVisible(false);
//                jl_cargo.setVisible(false);
//                jl_contra.setVisible(false);
//                jl_modificableU.setVisible(false);
                tf_usuario.setEnabled(false);
                tf_contra.setEnabled(false);
                rb_planta.setEnabled(false);
                rb_sucursal.setEnabled(false);

//                jl_ocupacion.setVisible(true);
//                jl_horario.setVisible(true);
//                jl_tiempo.setVisible(true);
//                jl_semanas.setVisible(true);
//                jl_sueldo.setVisible(true);
//                jl_modificableS.setVisible(true);
                tf_ocupacion.setEnabled(true);
                tf_ocupacion.setText(p.getOcupacion());

                tf_horario.setEnabled(true);
                tf_horario.setText(p.getHorario());

                ff_tiempo.setEnabled(true);
                ff_tiempo.setText(p.getSemanasContratado() + "");

                ff_sueldo.setEnabled(true);
                ff_sueldo.setText(p.getSueldo() + "");

                tf_usuario.setText("");
                tf_contra.setText("");
                
                cb_tipo.setSelectedIndex(1);
            }
        }
    }//GEN-LAST:event_cb_personasItemStateChanged

    private void jb_colorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_colorActionPerformed

        jb_color.setBackground(
                JColorChooser.showDialog(this, "Seleccione el color del carro.", jb_color.getBackground())
        );

    }//GEN-LAST:event_jb_colorActionPerformed

    private void cb_registradorItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cb_registradorItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_cb_registradorItemStateChanged

    private void jb_crearArtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_crearArtActionPerformed
        if (entrar()) {
            String titulo, descripcion, editorial;
            Color color;
            int tamaño;
            float puntuacion;
            Persona registrador = null;

            try {
                titulo = tf_titulo.getText();
                descripcion = ta_descripcionArt.getText();
                editorial = tf_editorial.getText();
                color = jb_color.getBackground();
                tamaño = Integer.parseInt(ff_tamano.getValue().toString());
                puntuacion = Float.parseFloat(sp_puntuacion.getValue().toString());
                if (cb_registrador.getSelectedIndex()>=0) {
                    registrador = (Persona) ((DefaultComboBoxModel)cb_registrador.getModel()).getElementAt(cb_registrador.getSelectedIndex());
                }
                
                if (cb_listaArt.getSelectedIndex() == 0) {

                    String descripComic = ta_descripcionComic.getText();
                    int estado = sl_estado.getValue();
                    int volumen = Integer.parseInt(ff_volumen.getText());
                    
                    Articulo a = 
                            new Comic(volumen, descripComic, estado, titulo, color, descripcion, editorial, tamaño, puntuacion, registrador);
                    aa.getArticulos().add(a);
                    DefaultComboBoxModel m = (DefaultComboBoxModel) cb_listaArt.getModel();
                    m.addElement(a);

                    estadoOperacion(true);
                } else if (cb_listaArt.getSelectedIndex() == 1) {
                    String casaElaboracion, pais;
                    int edicion = Integer.parseInt(ff_edicion.getText());

                    casaElaboracion = tf_casaElaboracion.getText();
                    pais = tf_pais.getText();
                    
                    Articulo a = 
                            new Juego(edicion, casaElaboracion, pais, titulo, color, descripcion, editorial, tamaño, puntuacion, registrador);

                    aa.getArticulos().add(a);
                    DefaultComboBoxModel m = (DefaultComboBoxModel) cb_listaArt.getModel();
                    m.addElement(a);

                    estadoOperacion(true);
                } else if (cb_listaArt.getSelectedIndex() == 2) {
                    String descripFigura = ta_descripcionComic.getText();
                    String instrucciones = ta_instrucciones.getText();
                    int tiempo = Integer.parseInt(ff_garantía.getText());
                    
                    Articulo a = 
                            new Figura(descripFigura, instrucciones, tiempo, titulo, color, descripcion, editorial, tamaño, puntuacion, registrador);
                    aa.getArticulos().add(a);
                    DefaultComboBoxModel m = (DefaultComboBoxModel) cb_listaArt.getModel();
                    m.addElement(a);
                }
                aa.escribirArticulos();
                limpiarCampos2();
                cargarPersonasCB();

            } catch (Exception e) {
                estadoOperacion(false);
            }

        }

    }//GEN-LAST:event_jb_crearArtActionPerformed

    private void jb_modificarArtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_modificarArtActionPerformed
        if (entrar()) {
            String titulo, descripcion, editorial;
            Color color;
            int tamaño;
            float puntuacion;
            Persona registrador = null;

            try {
                titulo = tf_titulo.getText();
                descripcion = ta_descripcionArt.getText();
                editorial = tf_editorial.getText();
                color = jb_color.getBackground();
                tamaño = Integer.parseInt(ff_tamano.getValue().toString());
                puntuacion = Float.parseFloat(sp_puntuacion.getValue().toString());
                if (cb_registrador.getSelectedIndex()>=0) {
                    registrador = (Persona) ((DefaultComboBoxModel)cb_registrador.getModel()).getElementAt(cb_registrador.getSelectedIndex());
                }

                if (aa.getArticulos().get(cb_listaArt.getSelectedIndex()) instanceof Comic) {
                    String decripComic = ta_descripcionComic.getText();
                    
                    Comic c = ((Comic) aa.getArticulos().get(cb_listaArt.getSelectedIndex()));
                    c.setDescripcionComic(decripComic);
                    
                    c.setTitulo(titulo);
                    c.setDescripcionArticulo(descripcion);
                    c.setEditorial(editorial);
                    c.setColor(color);
                    c.setTamaño(tamaño);
                    c.setPuntuacion(puntuacion);

                    estadoOperacion(true);
                } else if (aa.getArticulos().get(cb_listaArt.getSelectedIndex()) instanceof Juego) {

                    String pais = tf_pais.getText();
                    
                    Juego c = ((Juego) aa.getArticulos().get(cb_listaArt.getSelectedIndex()));
                    c.setPaisDondeSeHizo(pais);
                    
                    c.setTitulo(titulo);
                    c.setDescripcionArticulo(descripcion);
                    c.setEditorial(editorial);
                    c.setColor(color);
                    c.setTamaño(tamaño);
                    c.setPuntuacion(puntuacion);

                    estadoOperacion(true);
                } else if (aa.getArticulos().get(cb_listaArt.getSelectedIndex()) instanceof Figura){
                    String decripFigura = ta_descripcionComic.getText();
                    
                    Figura c = ((Figura) aa.getArticulos().get(cb_listaArt.getSelectedIndex()));
                    c.setDescripcionFigura(decripFigura);
                    
                    c.setTitulo(titulo);
                    c.setDescripcionArticulo(descripcion);
                    c.setEditorial(editorial);
                    c.setColor(color);
                    c.setTamaño(tamaño);
                    c.setPuntuacion(puntuacion);

                    estadoOperacion(true);
                }
                aa.escribirArticulos();
                cargarArticulosCB();
            } catch (Exception e) {
                estadoOperacion(false);
            }
            limpiarCampos();
        }
    }//GEN-LAST:event_jb_modificarArtActionPerformed

    private void jb_eliminarArtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_eliminarArtActionPerformed
        if (entrar()) {
            try {
                if (cb_listaArt.getSelectedIndex() >= 0) {
                    aa.getArticulos().remove(cb_listaArt.getSelectedIndex());
                    DefaultComboBoxModel m = (DefaultComboBoxModel) cb_listaArt.getModel();
                    m.removeElementAt(cb_listaArt.getSelectedIndex());
                    estadoOperacion(true);
                    aa.escribirArticulos();
                    cargarArticulosCB();
                }
            } catch (Exception e) {
                estadoOperacion(false);
            }
        }
    }//GEN-LAST:event_jb_eliminarArtActionPerformed

    private void cb_artItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cb_artItemStateChanged
        //if (evt.getStateChange() == 2) {
        if (cb_art.getSelectedIndex() == 0) {

            //Juego
            ff_edicion.setEnabled(false);
            tf_casaElaboracion.setEnabled(false);
            tf_pais.setEnabled(false);

            //Figura
//                ta_descripsionComic.setEnabled(false);
            ta_instrucciones.setEnabled(false);
            ff_garantía.setEnabled(false);

            //Comic
            sl_estado.setEnabled(true);
            ta_descripcionComic.setEnabled(true);
            ff_volumen.setEnabled(true);

        } else if (cb_art.getSelectedIndex() == 1) {

            //Figura
//                ta_descripsionComic.setEnabled(false);
            ta_instrucciones.setEnabled(false);
            ff_garantía.setEnabled(false);

            //Comic
            sl_estado.setEnabled(false);
            ta_descripcionComic.setEnabled(false);
            ff_volumen.setEnabled(false);

            //Juego
            ff_edicion.setEnabled(true);
            tf_casaElaboracion.setEnabled(true);
            tf_pais.setEnabled(true);

        } else {

            //Comic
            sl_estado.setEnabled(false);
//                ta_descripsionComic.setEnabled(false);
            ff_volumen.setEnabled(false);

            //Juego
            ff_edicion.setEnabled(false);
            tf_casaElaboracion.setEnabled(false);
            tf_pais.setEnabled(false);

            //Figura
            ta_descripcionComic.setEnabled(true);
            ta_instrucciones.setEnabled(true);
            ff_garantía.setEnabled(true);

        }
        //}
    }//GEN-LAST:event_cb_artItemStateChanged

    private void jTabbedPane1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTabbedPane1FocusGained
        DefaultTableModel t = (DefaultTableModel) jt_personas.getModel();

        for (int i = t.getRowCount() - 1; i >= 0; i--) {
            t.removeRow(i);
        }

        for (Persona p : ap.getPersonas()) {

            String s = (p instanceof Gerente) ? "Gerente" : "Persona General";

            Object[] so = new Object[]{
                p,
                s
            };
            t.addRow(so);
            jt_personas.setModel(t);

        }
    }//GEN-LAST:event_jTabbedPane1FocusGained

    private void cb_emisorItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cb_emisorItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_cb_emisorItemStateChanged

    private void cb_receptorItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cb_receptorItemStateChanged
        if (evt.getStateChange() == 2) {
            if (cb_emisor.getSelectedIndex() == cb_receptor.getSelectedIndex() && cb_emisor.getSelectedIndex() != -1) {
                cb_receptor.setSelectedIndex(-1);
            }
        }
    }//GEN-LAST:event_cb_receptorItemStateChanged

    private void bt_enviarMensajeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_enviarMensajeActionPerformed

        try {
            if (cb_emisor.getSelectedIndex() != -1 && cb_receptor.getSelectedIndex() != -1) {

                Mensaje m = new Mensaje((Persona) cb_emisor.getSelectedItem(), (Persona) cb_receptor.getSelectedItem(), text.getText());

                DefaultComboBoxModel mEmisor = (DefaultComboBoxModel) cb_emisor.getModel();
                DefaultComboBoxModel mReceptor = (DefaultComboBoxModel) cb_receptor.getModel();

                ((Persona) mEmisor.getElementAt(cb_emisor.getSelectedIndex())).getMensajesEnviados().add(m);
                ((Persona) mReceptor.getElementAt(cb_emisor.getSelectedIndex())).getMensajesRecibidos().add(m);

                DefaultTableModel t = (DefaultTableModel) jt_mensajes.getModel();
                Object[] r = new Object[]{
                    (Persona) cb_emisor.getSelectedItem(),
                    (Persona) cb_receptor.getSelectedItem(),
                    m
                };

                //Agregamos la fila a la tabla
                t.addRow(r);
                jt_mensajes.setModel(t);

                estadoOperacion(true);

                //Lo agregamos al registro de mensajes (clase de binario)
                rm.getMensajes().add(m);
                rm.escribirMensajes();

                cb_emisor.setSelectedIndex(-1);
                cb_receptor.setSelectedIndex(-1);
                text.setText("");

            } else {
                estadoOperacion(false);
            }
        } catch (Exception e) {
            estadoOperacion(false);
        }
    }//GEN-LAST:event_bt_enviarMensajeActionPerformed

    private void cb_listaArtItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cb_listaArtItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_cb_listaArtItemStateChanged

    private void jb_limpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_limpiarActionPerformed
        limpiarCampos();
    }//GEN-LAST:event_jb_limpiarActionPerformed

    private void jb_limpiar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_limpiar1ActionPerformed
        limpiarCampos2();
    }//GEN-LAST:event_jb_limpiar1ActionPerformed

    private void mostrarDatosPersona(Persona p) {

        String id = Long.toString(p.getIdentificacion());
        for (int i = 13; i > id.length(); i--) {
            id = "0" + id;
        }
        try {
            id = id.substring(0, 4) + "-" + id.substring(4, 8) + "-" + id.substring(8, 13);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Ha ocurrido un error.", "Error", JOptionPane.ERROR_MESSAGE);
        }

        ff_identificacion.setText(id);
        tf_nombre.setText(p.getNombrePersona());
        ff_edad.setText(p.getEdad() + "");
        ff_altura.setText(p.getAltura() + "");
        ff_peso.setText(p.getPeso() + "");

        if (p.getSexo().equals("Masculino")) {
            rb_masculino.setSelected(true);
        }

        if (p.getEstadoCivil().equals("Soltero")) {
            rb_soltero.setSelected(true);
        } else if (p.getEstadoCivil().equals("Casado")) {
            rb_casado.setSelected(true);
        } else if (p.getEstadoCivil().equals("Divorciado")) {
            rb_divorciado.setSelected(true);
        } else {
            rb_viudo.setSelected(true);
        }

    }

    /*
    private void modificarAtributo(){
            try{
                if(cb_personas.getSelectedIndex()>0){
                    
                    if(contactos.get(cb_personas.getSelectedIndex()-1)instanceof Gerente){
                        Gerente p = (Gerente)cb_personas.getSelectedItem();
                        
                        String usuario = JOptionPane.showInputDialog("Ingrese un nuevo usuario:");
                        p.setUsuario(usuario);
                    
                        estadoOperacion(true);
                    }else{
                        PersonaGeneral p = (PersonaGeneral)cb_personas.getSelectedItem();
                        
                        Float sueldo = Float.parseFloat(JOptionPane.showInputDialog("Ingrese un nuevo sueldo:"));
                        p.setSueldo(sueldo);
                        
                        estadoOperacion(true);
                    }        
                }
            
            }catch(Exception e){
                estadoOperacion(false);
            }
    }
     */
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    public boolean entrar() {
        try {
            String password = JOptionPane.showInputDialog(this, "Ingrese la contraseña:", "Verificación.", JOptionPane.QUESTION_MESSAGE);
            boolean flag;
            if (password.equals("clau123")) {
                JOptionPane.showMessageDialog(null, "Contraseña correcta.", "Validación de Contraseña.", JOptionPane.INFORMATION_MESSAGE);
                return true;
            }
            JOptionPane.showMessageDialog(null, "Contraseña incorrecta.", "Validación de Contraseña.", JOptionPane.ERROR_MESSAGE);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error.", "Error", JOptionPane.ERROR_MESSAGE);
        }
        return false;
    }

    public void estadoOperacion(boolean b) {
        if (b) {
            JOptionPane.showMessageDialog(null, "Operación realizada con éxito.", "Estado de Operación", JOptionPane.INFORMATION_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(null, "La operación no pudo ser realizada.", "Estado de Operación", JOptionPane.ERROR_MESSAGE);
        }
    }

    public void limpiarCampos() {
        ff_identificacion.setText("");
        tf_nombre.setText("");
        ff_edad.setText("");
        ff_altura.setText("");
        ff_peso.setText("");
        rb_masculino.setSelected(true);
        rb_soltero.setSelected(true);

        tf_ocupacion.setText("");
        tf_horario.setText("");
        ff_tiempo.setText("");
        ff_sueldo.setText("");

        tf_usuario.setText("");
        tf_contra.setText("");
        rb_planta.setSelected(true);

        cb_personas.setSelectedIndex(-1);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bg_cargo;
    private javax.swing.ButtonGroup bg_estadoCivil;
    private javax.swing.ButtonGroup bg_sexo;
    private javax.swing.JButton bt_enviarMensaje;
    private javax.swing.JComboBox<String> cb_art;
    private javax.swing.JComboBox<String> cb_emisor;
    private javax.swing.JComboBox<String> cb_listaArt;
    private javax.swing.JComboBox<String> cb_personas;
    private javax.swing.JComboBox<String> cb_receptor;
    private javax.swing.JComboBox<String> cb_registrador;
    private javax.swing.JComboBox<String> cb_tipo;
    private javax.swing.JFormattedTextField ff_altura;
    private javax.swing.JFormattedTextField ff_edad;
    private javax.swing.JFormattedTextField ff_edicion;
    private javax.swing.JFormattedTextField ff_garantía;
    private javax.swing.JFormattedTextField ff_identificacion;
    private javax.swing.JFormattedTextField ff_peso;
    private javax.swing.JFormattedTextField ff_sueldo;
    private javax.swing.JFormattedTextField ff_tamano;
    private javax.swing.JFormattedTextField ff_tiempo;
    private javax.swing.JFormattedTextField ff_volumen;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JButton jb_color;
    private javax.swing.JButton jb_crear;
    private javax.swing.JButton jb_crearArt;
    private javax.swing.JButton jb_eliminar;
    private javax.swing.JButton jb_eliminarArt;
    private javax.swing.JButton jb_limpiar;
    private javax.swing.JButton jb_limpiar1;
    private javax.swing.JButton jb_modificar;
    private javax.swing.JButton jb_modificarArt;
    private javax.swing.JLabel jl_cargo;
    private javax.swing.JLabel jl_casaElaboracion;
    private javax.swing.JLabel jl_contra;
    private javax.swing.JLabel jl_desc;
    private javax.swing.JLabel jl_edicion;
    private javax.swing.JLabel jl_estado;
    private javax.swing.JLabel jl_garantia;
    private javax.swing.JLabel jl_horario;
    private javax.swing.JLabel jl_instrucciones;
    private javax.swing.JLabel jl_modificableS;
    private javax.swing.JLabel jl_modificableU;
    private javax.swing.JLabel jl_modificableU1;
    private javax.swing.JLabel jl_modificableU2;
    private javax.swing.JLabel jl_numeros;
    private javax.swing.JLabel jl_ocupacion;
    private javax.swing.JLabel jl_pais;
    private javax.swing.JLabel jl_semanas;
    private javax.swing.JLabel jl_semanas1;
    private javax.swing.JLabel jl_sueldo;
    private javax.swing.JLabel jl_tiempo;
    private javax.swing.JLabel jl_usuario;
    private javax.swing.JLabel jl_volumen;
    private javax.swing.JTable jt_mensajes;
    private javax.swing.JTable jt_personas;
    private javax.swing.JPanel panel;
    private javax.swing.JRadioButton rb_casado;
    private javax.swing.JRadioButton rb_divorciado;
    private javax.swing.JRadioButton rb_femenino;
    private javax.swing.JRadioButton rb_masculino;
    private javax.swing.JRadioButton rb_planta;
    private javax.swing.JRadioButton rb_soltero;
    private javax.swing.JRadioButton rb_sucursal;
    private javax.swing.JRadioButton rb_viudo;
    private javax.swing.JSlider sl_estado;
    private javax.swing.JSpinner sp_puntuacion;
    private javax.swing.JTextArea ta_descripcionArt;
    private javax.swing.JTextArea ta_descripcionComic;
    private javax.swing.JTextArea ta_instrucciones;
    private javax.swing.JTextArea text;
    private javax.swing.JTextField tf_casaElaboracion;
    private javax.swing.JTextField tf_contra;
    private javax.swing.JTextField tf_editorial;
    private javax.swing.JTextField tf_horario;
    private javax.swing.JTextField tf_nombre;
    private javax.swing.JTextField tf_ocupacion;
    private javax.swing.JTextField tf_pais;
    private javax.swing.JTextField tf_titulo;
    private javax.swing.JTextField tf_usuario;
    // End of variables declaration//GEN-END:variables

    AdminPersonas ap = new AdminPersonas();
    AdminArticulos aa = new AdminArticulos();
    RegistroMensajes rm = new RegistroMensajes();

    private void cargarPersonasCB() {
        cb_personas.setModel(new DefaultComboBoxModel(ap.getPersonas().toArray()));
        cb_emisor.setModel(new DefaultComboBoxModel(ap.getPersonas().toArray()));
        cb_receptor.setModel(new DefaultComboBoxModel(ap.getPersonas().toArray()));
        cb_registrador.setModel(new DefaultComboBoxModel(ap.getPersonas().toArray()));
        cb_personas.setSelectedIndex(-1);
        cb_emisor.setSelectedIndex(-1);
        cb_receptor.setSelectedIndex(-1);
        cb_registrador.setSelectedIndex(-1);
    }

    private void cargarArticulosCB() {
        cb_listaArt.setModel(new DefaultComboBoxModel(aa.getArticulos().toArray()));
        cb_listaArt.setSelectedIndex(-1);
    }

    private void cargarMensajes() {

        DefaultTableModel model = (DefaultTableModel) jt_mensajes.getModel();

        for (int i = model.getRowCount() - 1; i >= 0; i--) {
            model.removeRow(i);
        }

        for (Mensaje mensaje : rm.getMensajes()) {

            Object[] row = new Object[]{
                mensaje.getEmisor(),
                mensaje.getReceptor(),
                mensaje
            };
            model.addRow(row);
        }

        jt_mensajes.setModel(model);

    }

    private void limpiarCampos2() {
        tf_titulo.setText("");
        ta_descripcionArt.setText("");
        ta_descripcionComic.setText("");
        ta_instrucciones.setText("");
        jb_color.setBackground(Color.red);
        ff_tamano.setText("");
        tf_editorial.setText("");
        sp_puntuacion.setValue(100);
        cb_registrador.setSelectedIndex(-1);
        sl_estado.setValue(10);
        ff_volumen.setText("");
        ff_edicion.setText("");
        ff_garantía.setText("");
        tf_casaElaboracion.setText("");
        tf_pais.setText("");
        
        cb_listaArt.setSelectedIndex(-1);
    }
}
